apiVersion: apps/v1
kind: Deployment

metadata:
  name: image-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: image

  template:
    metadata:
      labels:
        app: image

    spec:
      containers:
        - name: image
          image: aiinferenceplatform-image:latest
          imagePullPolicy: Never

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"

          ports:
            - containerPort: 8003