FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8003

CMD uvicorn backend.services.image.app.main:app --host 0.0.0.0 --port 8003